#!/bin/bash


## Load the required modules
module load mpt
module load gcc

## compile


## compile with MPI:
mpicxx heat_parallel.cpp  -o heateqExe

## remove object files if there is any!:
# rm *.mod
# rm *.o

